### ISSUE TITLE
Great idea, but not working.

### ISSUE THREAD

**Issue by cmikeb1** [ricardoemerson/yaml-path-copy#5]
Example yml file:
```
foo:
  bar: value

bar:
  foo: 1
```

Result of trying to copy `bar.foo`:
`foo.bar.foo`

Result of trying to copy `foo.bar`:
`<root>`

**Comment by ricardoemerson** [comment]
Hi @cmikeb1,  this package was designed to work with single root key, like this:

```yaml
app:
  foo:
    bar: value

  bar:
    foo: value
```
